version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app # Mount source code for hot reload
    environment:
      - ENV=development
